update precommit

diff --git a/Scripts/precommit b/Scripts/precommit
--- a/Scripts/precommit
+++ b/Scripts/precommit
@@ -1,5 +1,7 @@
 #! /bin/zsh
 
+# readonly PROGNAME=$0:A
+# readonly SCRIPTSDIR=${PROGNAME%/precommit}
 
 checkFile() {
   local fname=$1
@@ -7,20 +9,15 @@ checkFile() {
 
   tmpfile=.precommit-tmp-file
 
-  # :0:FNAME means "stage 0 entry", or just "staged"
+  # :0:FNAME means 'stage 0 entry', or just "staged"
   git cat-file -p :0:"$fname" > $tmpfile
 
-  # Make sure shebang is zsh
-  # sed -i.bak '1 s/bin\/bash/bin\/zsh/' "$fname"
-  # rm "${fname}.bak"
-
-  # And if sed didn't work for some reason...
   shebang=$(head -n1 "$tmpfile")
   if [[ $shebang != */bin/zsh* ]]; then
     echo "ERROR $fname: wanted shebang == */bin/zsh*, got '$shebang'"
   fi
 
-  # Even though using Bash rules, Zsh is mostly similar.
+  # Even though using Bash rules, Zsh is similar enough.
   # Any Zsh-specific irregularities will have accompanying
   # `shellcheck disable` statements inline, or in the .shellcheckrc file
   shellcheck -f gcc -s bash "$tmpfile" | awk '{print "ERROR " $0; }'
@@ -53,8 +50,10 @@ main() {
   exec 1>&2
 
   local errs=
-  for fname in $(git diff --cached --name-only "$against"); do
-    for i in Scripts/build.sh Scripts/test.sh Scripts/precommit; do
+  for fname in $(git diff --cached --name-only "$against");
+    do
+    for i in Scripts/build.sh Scripts/test.sh Scripts/precommit;
+      do
       if [ "$fname" = "$i" ]; then
         local _errs=
         _errs=$(checkFile "$fname")
@@ -71,11 +70,26 @@ main() {
     done
   done
 
+  # cd $SCRIPTSDIR || echo "Couldn't cd to $SCRIPTSDIR" && exit 1
+  # _errs=$(./run_tests.sh)
+  # _status=$?
+  # if [ $_status -ne 0 ]; then
+  #   local msg=
+  #   msg=$(print_errors "$_errs")
+  #   if [ "$errs" = "" ]; then
+  #     errs="$msg"
+  #   else
+  #     errs="$errs\n$msg"
+  #   fi
+  # fi
+
   if [ "$errs" != "" ]; then
     echo "$errs"
     echo
     exit 1
   fi
+
+
 }
 
 main
